// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwM5Mmj2QAfLXprirqfZJy5bLv9ECN8C0',
    appId: '1:312604426077:web:492020fe303fe47463f2b4',
    messagingSenderId: '312604426077',
    projectId: 'farmezy-4bb19',
    authDomain: 'farmezy-4bb19.firebaseapp.com',
    storageBucket: 'farmezy-4bb19.firebasestorage.app',
    measurementId: 'G-8P70HCP9VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-dTb3_qImsSxBuIJFqACcYkQxD4xxgDU',
    appId: '1:312604426077:android:8d8ac2293eda977763f2b4',
    messagingSenderId: '312604426077',
    projectId: 'farmezy-4bb19',
    storageBucket: 'farmezy-4bb19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTZbFJ-o7gPRS8O_p_Ek8rrmiKqDPI0w',
    appId: '1:312604426077:ios:e0241a0ac831443863f2b4',
    messagingSenderId: '312604426077',
    projectId: 'farmezy-4bb19',
    storageBucket: 'farmezy-4bb19.firebasestorage.app',
    iosBundleId: 'com.example.farmezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTZbFJ-o7gPRS8O_p_Ek8rrmiKqDPI0w',
    appId: '1:312604426077:ios:e0241a0ac831443863f2b4',
    messagingSenderId: '312604426077',
    projectId: 'farmezy-4bb19',
    storageBucket: 'farmezy-4bb19.firebasestorage.app',
    iosBundleId: 'com.example.farmezy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwM5Mmj2QAfLXprirqfZJy5bLv9ECN8C0',
    appId: '1:312604426077:web:1d55a203b48a934f63f2b4',
    messagingSenderId: '312604426077',
    projectId: 'farmezy-4bb19',
    authDomain: 'farmezy-4bb19.firebaseapp.com',
    storageBucket: 'farmezy-4bb19.firebasestorage.app',
    measurementId: 'G-W31KQES19C',
  );
}
